"""implementar tablas estudiantes y docentes

Revision ID: d05c87c4a754
Revises: 
Create Date: 2026-05-24 22:24:36.709382

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd05c87c4a754'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('docentes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nombre', sa.String(), nullable=False),
    sa.Column('apellido', sa.String(), nullable=False),
    sa.Column('email', sa.String(), nullable=False),
    sa.Column('hash_contrasena', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_docentes_email'), 'docentes', ['email'], unique=True)
    op.create_index(op.f('ix_docentes_id'), 'docentes', ['id'], unique=False)
    op.create_table('estudiantes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nombre', sa.String(), nullable=False),
    sa.Column('apellido', sa.String(), nullable=False),
    sa.Column('email', sa.String(), nullable=False),
    sa.Column('hash_contrasena', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_estudiantes_email'), 'estudiantes', ['email'], unique=True)
    op.create_index(op.f('ix_estudiantes_id'), 'estudiantes', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_estudiantes_id'), table_name='estudiantes')
    op.drop_index(op.f('ix_estudiantes_email'), table_name='estudiantes')
    op.drop_table('estudiantes')
    op.drop_index(op.f('ix_docentes_id'), table_name='docentes')
    op.drop_index(op.f('ix_docentes_email'), table_name='docentes')
    op.drop_table('docentes')
    # ### end Alembic commands ###
