"""crear tabla de las clases

Revision ID: d807188d162e
Revises: d05c87c4a754
Create Date: 2026-05-31 04:40:23.624064

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd807188d162e'
down_revision: Union[str, Sequence[str], None] = 'd05c87c4a754'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('clase',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('materia', sa.String(), nullable=False),
    sa.Column('horario', sa.DateTime(), nullable=False),
    sa.Column('docente_id', sa.Integer(), nullable=True),
    sa.Column('qr', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['docente_id'], ['docentes.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('asistencia_clase_estudiante',
    sa.Column('clase_id', sa.Integer(), nullable=False),
    sa.Column('estudiante_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['clase_id'], ['clase.id'], ),
    sa.ForeignKeyConstraint(['estudiante_id'], ['estudiantes.id'], ),
    sa.PrimaryKeyConstraint('clase_id', 'estudiante_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('asistencia_clase_estudiante')
    op.drop_table('clase')
    # ### end Alembic commands ###
